### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wjczf123** [Aaditya-Singh/E2E-ECPE#1]
I have a qustion about dataset. I found that the corpus consists of 2843 documents. But Gao et al. writed that this corpus has 2403 documents (Table 1 in their paper).  And Li et al. and Fan et al. writed that this corpus has 2156 documents (see Table 3 and Table 1 in their paper). What caused this difference?

**Comment by shreeshail-23** [comment]
We could not find the dataset publicly since the web-links we found in previous publications were expired. We obtained the dataset from Prof. Lin Gui, University of Warwick, and it contained 2843 documents.

**Comment by wjczf123** [comment]
OK. Thank you a lot.
