### ISSUE TITLE
Results about ECPE 2-stage

### ISSUE THREAD

**Issue by wjczf123** [Aaditya-Singh/E2E-ECPE#2]
I have a detailed question. What does ECPE 2-stage mean in your paper? It means Indep, Inter-CE or Inter-EC in [1]?

[1] Emotion-Cause Pair Extraction: A New Task to Emotion Analysis in Texts, In ACL'2019

**Comment by wjczf123** [comment]
Another question is why you choose ISML-6 for ECPE-MLL instead of BERT? Is it the performance of ISML-6 exceeds BERT?
Thanks!

**Comment by Aaditya-Singh** [comment]
Thanks for your interest and apologies for the late response. ECPE 2-stage refers to the Inter-EC architecture in [Xia and Ding, 2019](https://arxiv.org/abs/1906.01267). Yes, we chose the  best-performing versions of the different methods as it's a fairly standard research practice which helps in further establishing our point. Another reason was that we already were comparing against BERT-based ECPE-2D.

**Comment by wjczf123** [comment]
Thanks for your reply. Best regards!
