### ISSUE TITLE
question about input text

### ISSUE THREAD

**Issue by jhwanflow** [Aaditya-Singh/E2E-ECPE#3]
thank you for your nice work and dataset!

I have a question about the format of input text.

```
def load_w2v(embedding_dim, embedding_dim_pos, train_file_path, embedding_path):
    print('\nload embedding...')

    words = []
    inputFile1 = open(train_file_path, 'r')
    for line in inputFile1.readlines():
        line = line.strip().split(',')
        emotion, clause = line[2], line[-1] 
        words.extend(emotion.lower().split() + clause.lower().split())
        # words extended by ['happy','the','thief','was','caught']

    words = set(words) # Collection of all unique words
    word_idx = dict((c, k + 1) for k, c in enumerate(words)) # Each word and its position
    word_idx_rev = dict((k + 1, c) for k, c in enumerate(words)) # Each word and its position

```
in this code, you extract  "emotion" (line[2]) as well as "clause" (line[-1]).

I think  the variable "emotion" might be a crucial hint for the model to predict whether this clause is emotion clause or not, because if "emotion" is null that means this is not a emotion clause.

so what I want to ask is that, do you have some experimental results where "emotion" is not included in input text?

for example ['happy','the','thief','was','caught'] => ['the','thief','was','caught'] .

thank you again and  have a nice day!

**Comment by Aaditya-Singh** [comment]
Hi Lee, thanks for your interest in our work. The `load_w2v` function only serves the purpose to [map](https://github.com/Aaditya-Singh/E2E-ECPE/blob/main/utils/prepare_data.py#L26) the word indices to their corresponding [GloVe embeddings](https://github.com/Aaditya-Singh/E2E-ECPE/blob/main/data_combine_eng/w2v_200.txt). 

The input `x` to the model during [training](https://github.com/Aaditya-Singh/E2E-ECPE/blob/main/E2E_PextE.py#L171) and [inference](https://github.com/Aaditya-Singh/E2E-ECPE/blob/main/E2E_PextE.py#L197) comes via the `load_data_pair`. Inside this function, [only clause words are used](https://github.com/Aaditya-Singh/E2E-ECPE/blob/main/utils/prepare_data.py#L86) for constructing `x`.

P.S. I'd highly recommend using [VSCode debugger](https://code.visualstudio.com/docs/introvideos/debugging) which allows you to monitor the code flow in real time for queries such as this.

Hope this helps and have a nice day yourself!

**Comment by jhwanflow** [comment]
oh i see. i missed load_data_pair. thank you for your kind reply!
